name: On Challenge Review Commented

on:
  issue_comment:
    types:
    - created

env:
  PR_REVIEWERS: ${{ secrets.PR_REVIEWERS }}

jobs:
  signoff:
    # Run only if the issue is related to PR && labelled as 'review-completed' && commenter is assignee
    if: ${{ github.event.issue.pull_request }}
    # if: ${{ github.event.issue.pull_request }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ github.event.comment.user.login == github.event.issue.assignee.login }}
    name: 'Sign-off challenge'

    runs-on: ubuntu-latest

    steps:
    - name: Get event payload
      # If commenter is one of PR_REVIEWERS && comment is '/helloworld'
      # if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/helloworld' }}
      shell: pwsh
      run: |
        Write-Host '${{ toJSON(github.event) }}'

    - name: Get checkpoints
      id: checkpoint
      shell: pwsh
      run: |
        $hasValidLabel = [System.Convert]::ToBoolean("${{ contains(github.event.issue.labels.*.name, 'review-completed') }}")
        $isCommenterAssignee = [System.Convert]::ToBoolean("${{ github.event.comment.user.login == github.event.issue.assignee.login }}")
        $isValidCommenter = [System.Convert]::ToBoolean("${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }}")
        $isHelloWorld = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/helloworld' }}")
        $isAswaSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/aswasignoff' }}")
        $isGhaSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/ghasignoff' }}")
        $isSocialSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/socialsignoff' }}")
        $isAppSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/appsignoff' }}")
        $isRepoSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/reposignoff' }}")
        $isRetroSignoff = [System.Convert]::ToBoolean("${{ github.event.comment.body == '/retrosignoff' }}")

        echo "::set-output name=hasValidLabel::$hasValidLabel"
        echo "::set-output name=isCommenterAssignee::$isCommenterAssignee"
        echo "::set-output name=isValidCommenter::$isValidCommenter"
        echo "::set-output name=isHelloWorld::$isHelloWorld"
        echo "::set-output name=isAswaSignoff::$isAswaSignoff"
        echo "::set-output name=isGhaSignoff::$isGhaSignoff"
        echo "::set-output name=isSocialSignoff::$isSocialSignoff"
        echo "::set-output name=isAppSignoff::$isAppSignoff"
        echo "::set-output name=isRepoSignoff::$isRepoSignoff"
        echo "::set-output name=isRetroSignoff::$isRetroSignoff"

    - name: Get outputs
      shell: pwsh
      run: |
        echo ${{ steps.checkpoint.outputs.hasValidLabel }}
        echo ${{ steps.checkpoint.outputs.hasValidLabel}}
        echo ${{ steps.checkpoint.outputs.isCommenterAssignee }}
        echo ${{ steps.checkpoint.outputs.isValidCommenter }}
        echo ${{ steps.checkpoint.outputs.isHelloWorld }}
        echo ${{ steps.checkpoint.outputs.isAswaSignoff }}
        echo ${{ steps.checkpoint.outputs.isGhaSignoff }}
        echo ${{ steps.checkpoint.outputs.isSocialSignoff }}
        echo ${{ steps.checkpoint.outputs.isAppSignoff }}
        echo ${{ steps.checkpoint.outputs.isRepoSignoff }}
        echo ${{ steps.checkpoint.outputs.isRetroSignoff }}

    # - name: Record challenge ASWA
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/aswasignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "aswa", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

    # - name: Record challenge GHA
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/ghasignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "gha", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

    # - name: Record challenge SOCIAL
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/socialsignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "social", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

    # - name: Record challenge APP
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/appsignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "app", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

    # - name: Record challenge REPO
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/reposignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "repo", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

    # - name: Record challenge RETRO
    #   if: ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.comment.body == '/retrosignoff' }}
    #   uses: joelwmale/webhook-action@2.1.0
    #   with:
    #     url: ${{ secrets.FLOW_URL }}
    #     body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "retro", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_aswa:
  #   # Run only if the issue is related to PR && comment is '/aswasignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/aswasignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for ASWA'

  #   runs-on: ubuntu-latest

  #   steps:
  #   # - name: Get event payload
  #   #   shell: pwsh
  #   #   run: |
  #   #     Write-Host '${{ toJSON(github.event) }}'

  #   # - name: Get event details
  #   #   shell: pwsh
  #   #   run: |
  #   #     Write-Host '* isPR: ${{ github.event.issue.pull_request }}'
  #   #     Write-Host '* body: ${{ github.event.comment.body }}'
  #   #     Write-Host '* isValidComment: ${{ github.event.comment.body == '/helloworld' }}'
  #   #     Write-Host '* commenter: ${{ github.event.comment.user.login }}'
  #   #     Write-Host '* isValidReviewer: ${{ contains(secrets.PR_REVIEWERS, github.event.comment.user.login) }}'
  #   #     Write-Host '* isAssigneeReviewer: ${{ github.event.issue.assignee.login == github.event.comment.user.login }}'
  #   #     Write-Host '* labels: ${{ toJSON(github.event.issue.labels.*.name) }}'
  #   #     Write-Host '* containLabel: ${{ contains(github.event.issue.labels.*.name, 'ops') }}'
  #   #     Write-Host '* containLabel: ${{ contains(github.event.issue.labels.*.name, 'review-completed') }}'

  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "aswa", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_gha:
  #   # Run only if the issue is related to PR && comment is '/ghasignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/ghasignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for GHA'

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "gha", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_social:
  #   # Run only if the issue is related to PR && comment is '/socialsignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/socialsignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for Social'

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "social", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_app:
  #   # Run only if the issue is related to PR && comment is '/appsignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/appsignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for App'

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "app", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_repo:
  #   # Run only if the issue is related to PR && comment is '/reposignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/reposignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for Repo'

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "repo", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'

  # approve_signoff_retro:
  #   # Run only if the issue is related to PR && comment is '/retrosignoff' && labelled as 'review-completed' && commenter is one of PR_REVIEWERS && commenter is assignee
  #   if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == '/retrosignoff' }} && ${{ contains(github.event.issue.labels.*.name, 'review-completed') }} && ${{ contains(env.PR_REVIEWERS, github.event.comment.user.login) }} && ${{ github.event.issue.assignee.login == github.event.comment.user.login }}
  #   name: 'Approve Signoff for Retro'

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send webhook request to record challenge
  #     uses: joelwmale/webhook-action@2.1.0
  #     with:
  #       url: ${{ secrets.FLOW_URL }}
  #       body: '{"gitHubId": "${{ github.event.issue.user.login }}", "challengeType": "retro", "timestamp": "${{ github.event.issue.comment.created_at }}", "prId": ${{ github.event.issue.number }} }'
